# Generated by Django 3.1.7 on 2021-04-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drinks_foods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drinks',
            new_name='drink',
        ),
        migrations.RenameModel(
            old_name='foods',
            new_name='food',
        ),
    ]
