# Generated by Django 3.1.7 on 2021-04-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210413_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='drink',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
