# Generated by Django 3.1.7 on 2021-04-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210415_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
